### PR TITLE
(OLD) feat(breaking): Upgrade to Prisma 5.1.0

### PR DESCRIPTION
**Pull request by janpio**
Initial PR to try to fix https://github.com/arthurfiorette/prisma-json-types-generator/issues/113.

Note, that I have no idea what I am doing. I looked at what was being output by the failing tests, and then stupidly made things not fail anymore. I might totally have misunderstood how this should be done. For that case, my edits would at least point to all the locations where Prisma 5.0.0 changed some values in a way that adaptations are needed in some way.

### CODE REVIEW

**Comment by arthurfiorette** [comment]
I saw that there was 3 branches relative to prisma 5.0+ updates, I'll use this one to support prisma 5.1 directly. I'm also doing some rewrites and code commenting to help maintain this thing in which I forgot some of its parts :)

**Comment by janpio** [comment]
Yes, that makes most sense. This branch here only went to 5.0 and fixed as much as I could. It is a good basis to build on probably.

I actually started with a branch that went directly from 4.x to 5.1, but then I had failures both triggered by 5.0 and 5.1 - without understanding which one was caused which. And then another one was just building on top of this one to see the failures by 5.1 - but I had no idea how to fix them, so I only create the 5.0 branch as a PR here :D 

Good luck!

**Comment by arthurfiorette** [comment]
Update: I'm having to almost rewrite the package, since there are many modifications in the typing, specially having to double check typings with where previously was `Enumerate`s. I'll push some draft code here tomorrow.

I'd like to write unit tests alongside this changes to ensure I'm not forgetting some edge case, do you have some good way of testing client generated types? I did not have time to look up how prisma is doing tests on its generators...

**Comment by janpio** [comment]
Would it maybe make sense to release a fix for Prisma 5.0 first then?
Next week someone from the team can help you understand any type changes if needed.

**Comment by tuarrep** [comment]
I have some use cases for this package right now, and Prisma 5 support is required. 

So ping me if you want me to test something. 
I'll be happy to help with this in the coming days.

**Comment by arthurfiorette** [comment]
I'll do things right this way and write useful tests from the beginning. Current PR is a WIP but I can list these changes/features for now:

- Overhaul testing, `tsd` multiple prisma schema to automate multiple prisma versions and experimental options testing.
- Package rewrite.
- I'd want to release alongside with #112

I was _forced_ to rewrite this package because practically all types were changed during this 5.0/5.1 upgrade. For now, no prisma bugs were found, only some inconsistencies in which I'll be describing here later...

I coded this until 1.15am while livestreaming on twitch (t.tv/arthurfiorette btw). A lot of progress was done, but there's work left until first review. Also added some `console.debug` statements to debug.

**Comment by arthurfiorette** [comment]
Oopsie 😅, I tried to push and got access denied. @janpio would I be able to push to `prisma/prisma-json-types-generator`? Or I need to create another branch in this repo?

**Comment by arthurfiorette** [comment]
Also, is prisma v4 LTS or have extended support? I was thinking of dropping support to v4 in this generator as a result of the changes in the dts...

**Comment by janpio** [comment]
> @janpio would I be able to push to `prisma/prisma-json-types-generator`? Or I need to create another branch in this repo?

I would if I could. Usually there is a small `Allow edits by maintainers` checkbox on the right sidebar, but not on this PR 😕 
image
image


> Also, is prisma v4 LTS or have extended support? I was thinking of dropping support to v4 in this generator as a result of the changes in the dts...

No, we only develop new versions - but of course a big share of our users are on 4.x still.
But maybe you just tell them to use the older version.

**Comment by arthurfiorette** [comment]
> I would if I could. Usually there is a small Allow edits by maintainers checkbox on the right sidebar, but not on this PR 😕

Maybe its in a org setting? idk

> But maybe you just tell them to use the older version.

Awesome, I'll do this.

**Comment by arthurfiorette** [comment]
Moving to #131 so that I can work on it...

**Pull request closed without merging**
