### PR TITLE
feat(breaking): Upgrade to Prisma 5.1.0

### PR DESCRIPTION
**Pull request by arthurfiorette**
See #128 and #113.

Current status: 

- [x] Better testing with tsd
- https://github.com/arthurfiorette/prisma-json-types-generator/issues/103
  - [x] Normal usage
  - [x] ~Preview features~ _not needed for now_
  - [x] Strings for type literals
  - [x] Enum support
  - [x] ~More types?~ _not needed for now_
- [x] https://github.com/arthurfiorette/prisma-json-types-generator/issues/112
  - [x] Added `allowAny` option
- [x] https://github.com/arthurfiorette/prisma-json-types-generator/issues/117
  - [x] Support with `![<literal>]` syntax
  - [x] Testing with `Json?` and `Json[]` types.
- [x] Removed unused async code.
- [x] Better error handling & support to partial generation.
- [x] README rewrite _(Help wanted here 😅)_
  - [x] Normal usage
  - [x] Arrays and optional
  - [x] Literal types
  - [x] Configuration example
  - [x] Fix types
- [x] Databases
  - [x] Postgres
  - [x] Mongodb
  - [x] Sqlite
  - [x] MySql
  - [x] CockroachDB
  - [x] Microsoft SQL Server

### CODE REVIEW

**Comment by cpojer** [comment]
I'm happy to verify whether this version works in my codebase. Could you publish this as an alpha/beta/nightly on npm once it is ready?

**Comment by arthurfiorette** [comment]
Hey @cpojer and others. I think most of the work has been done and I verified it with tests.

I released `@beta` 3.0.0 tag.

https://www.npmjs.com/package/prisma-json-types-generator?activeTab=versions

```sh
npm install prisma-json-types-generator@beta
```

Could someone give feedback about it? I'm expecting a bug or two but it should work fine.

**Comment by stonexer** [comment]
> 

It looks like the `/dist` didn't include in prisma-json-types-generator@3.0.0-beta.1

```
Error: Generator "prisma-json-types-generator" failed:

Error: Cannot find module './dist/generator.js'
```

**Comment by arthurfiorette** [comment]
Omg haha no way. Lets just pretend this never happened and the first version is `beta.2`.

**Comment by cpojer** [comment]
With `beta.2`, `prisma generate` errors with this :
> ENOENT: no such file or directory, open 'node_modules/.pnpm/prisma-json-types-generator@3.0.0-beta.2_prisma@5.0.0_typescript@5.1.6/node_modules/prisma-json-types-generator/assets/namespace.d.ts'

Would you mind including the assets folder as well?

**Comment by arthurfiorette** [comment]
done!

**Comment by cpojer** [comment]
Awesome, I tried `3.0.0-beta.3` in my project together with Prisma 5.1.0. The primary problem I seem to be running into is that this version appears to set all scalar fields that are not marked as custom Json types (via `/// [type]`) as `unknown` in my code, therefore breaking basically everything that is not using json-types. I can patch it by adding `/// [string]` to individual types, but this should probably be fixed in the library here first before I continue with the upgrade.

Example (I removed a few fields from the model here):
```
model User {
  id             Int             @id @default(autoincrement())
  access         Role            @default(User)
  character      String
  /// [CharacterNameEntry]
  characters     Json[]
  displayName    String
  email          String          @unique
  locale         String          @default("en_US")
  username       String          @unique
}
```

 CleanShot 2023-08-14 at 11 28 24@2x

**Comment by arthurfiorette** [comment]
@cpojer i was playing around with allowAny and #112 spec.

**Comment by cpojer** [comment]
My point is that it is too wide and doesn't just turn `Json` types to `unknown`, but other scalar types like `string`, too.

**Comment by arthurfiorette** [comment]
Oh I see. I'll fix it asap.

Should we let `unknown` as default? I can argue so, as someone would use this generator to enforce typings and unknown would be better. Also seems to be a safer-first approach for new prisma users and just a temporary `allowAny` to incrementally migrate existing schemas.

**Comment by cpojer** [comment]
I think `unknown` for Json types that are not annotated makes sense, yes.

**Comment by cpojer** [comment]
Update, using `3.0.0-beta.3` plus these two workarounds:
* `allowAny = true` in the generator config sidesteps the unknown scalar issue.
* The `namespace` config option appears to be unused and all types that are printed are global. For now, all inline types can be replaced with `/// [PrismaJson.MyType]` etc.

This allowed me to successfully upgrade to Prisma 5.1.0 without any type errors. Awesome work!

**Comment by elijaholmos** [comment]
In my codebase, I installed `3.0.0-beta.3` with pnpm and re-ran the generator. First try yielded a "Property 'x' does not exist on 'CustomType'" error. I followed @cpojer's suggestion in the second bullet point above, and the TypeError disappeared.

For clarity: it was necessary to change all my comments in the schema from `/// [CustomType]` to `/// [PrismaJson.CustomType]` in order for version `3.0.0-beta.3` to properly work. I have never used the `namespace` option in my configuration.

**Comment by arthurfiorette** [comment]
@cpojer, @elijaholmos `beta.4` released now, happy to fix more bugs before oficial `3.0.0` :)

**Comment by cpojer** [comment]
Awesome, I can confirm that beta 4 fixes both issues!

**Comment by arthurfiorette** [comment]
Well, then I'll just leave this **stable** `beta4` version open for a week or two and collect feedback, then I'll release it as `3.0.0`. Anyone from the future, feel free to report any bug in this beta.

**Comment by jakeleventhal** [comment]
Can confirm `3.0.0-beta.4` works for me

**Comment by elijaholmos** [comment]
`3.0.0-beta.4` works as expected when swapped in as a replacement for `v2.5.0` with Prisma `v5.1.1`

**Comment by yeongjet** [comment]
Good job, you save my project, bro.

**Comment by renatoaraujoc** [comment]
Hey @arthurfiorette, when you're merging this? Seems like its working :)

**Comment by bbonamin** [comment]
I'm happy to say too that `3.0.0-beta.4` has allowed me to upgrade prisma from `4.11.0` to `5.2.0` and keep the prisma-json-types-generator functionality. Many thanks!

**Comment by arthurfiorette** [comment]
Apparently, some types have different names under different databases, like `JsonValue | null` and `InputJsonValue | null` or `InputJsonValue | InputJsonValue | null`, for postgres and mongodb respectively.

I've added more TODOS to test w/ other dbs. Postgres as default way and mongo (#142) are already working 🔥

**Comment by arthurfiorette** [comment]
I improved the README but would love some feedback. _English is not my native language and I now it will have typos XD_

**Comment by arthurfiorette** [comment]
Everything in the TODO list was done. Releasing v3.0.0... Thanks everyone for contributing!

**Pull request merged**
